/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        // Design System Colors
        surface: {
          DEFAULT: "#f6fafe",
          dim: "#d6dade",
          bright: "#f6fafe",
          "container-lowest": "#ffffff",
          "container-low": "#f0f4f8",
          "container": "#eaeef2",
          "container-high": "#e4e9ed",
          "container-highest": "#dfe3e7",
          white: "#FFFFFF",
          variant: "#dfe3e7",
        },
        "on-surface": {
          DEFAULT: "#171c1f",
          variant: "#44474c",
        },
        "inverse-surface": "#2c3134",
        "inverse-on-surface": "#edf1f5",
        outline: {
          DEFAULT: "#75777d",
          variant: "#c5c6cd",
        },
        "surface-tint": "#515f74",
        primary: {
          DEFAULT: "#006c49",
          container: "#10b981",
          "on-primary": "#ffffff",
          "on-primary-container": "#9eadc5",
          fixed: "#6ffbbe",
          "fixed-dim": "#4edea3",
          "on-primary-fixed": "#002113",
          "on-primary-fixed-variant": "#005236",
        },
        secondary: {
          DEFAULT: "#2b6954",
          container: "#adedd3",
          "on-secondary": "#ffffff",
          "on-secondary-container": "#54647a",
          fixed: "#b0f0d6",
          "fixed-dim": "#95d3ba",
          "on-secondary-fixed": "#002117",
          "on-secondary-fixed-variant": "#0b513d",
        },
        tertiary: {
          DEFAULT: "#55615a",
          container: "#99a69e",
          "on-tertiary": "#ffffff",
          "on-tertiary-container": "#c3a881",
          fixed: "#d9e6dd",
          "fixed-dim": "#bdcac1",
          "on-tertiary-fixed": "#281901",
          "on-tertiary-fixed-variant": "#574424",
        },
        error: {
          DEFAULT: "#B91C1C",
          container: "#ffdad6",
          "on-error": "#ffffff",
          "on-error-container": "#93000a",
        },
        success: "#15803D",
        background: "#f6fafe",
        "on-background": "#171c1f",
        "navy-deep": "#0F172A",
        "soft-bg": "#f0f7f4",
        "soft-border": "#e2e8f0",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        "display-lg": ["Inter"],
        "headline-lg": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "headline-md": ["Inter"],
        "title-lg": ["Inter"],
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        "label-md": ["Inter"],
        "label-sm": ["Inter"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "title-lg": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "500" }],
        "label-sm": ["11px", { lineHeight: "14px", fontWeight: "600" }],
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "16px",
        "margin-desktop": "48px",
        "container-max": "1440px",
        gutter: "24px",
      },
      boxShadow: {
        soft: "0 4px 20px rgba(15, 23, 42, 0.08)",
        "soft-focus": "0px 4px 12px rgba(51, 65, 85, 0.08)",
        elevated: "0px 10px 24px rgba(51, 65, 85, 0.12)",
      },
    },
  },
  plugins: [],
};
